title: Arredofrigo
email: info@arredofrigo.net
description: >-
  Progettazione ambienti e Attrezzature professionali, cucine, arredamenti per ristoranti, bar e pizzerie.
baseurl: "" # lascia vuoto se usi dominio personalizzato
url: "https://arredofrigo.net"
theme: jekyll-theme-minimal
locale: it-IT

# SEO
logo: /assets/img/logo.webp
plugins:
  - jekyll-include-cache
  - jekyll-datapage-generator
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Chi siamo"
    url: "/chi-siamo/"
  - title: "Realizzazioni"
    url: "/realizzazioni/"
  - title: "Servizi"
    url: "/servizi/"
  - title: "Prodotti"
    url: "/prodotti/"
  - title: "Contatti"
    url: "/contatti/"

# Google Analytics (opzionale)
google_analytics: ""

# Social
author:
  name: "Arredofrigo"
  links:
    - label: "WhatsApp"
      url: "http://wa.me/+390572952803"
    - label: "Email"
      url: "mailto:info@arredofrigo.net"
    - label: "Mappa"
      url: "https://maps.google.com/?q=Arredofrigo+Pieve+a+Nievole"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - .bundle
  - vendor
  - script-utili

page_gen-dirs: true

page_gen:
  - data: prodotti     # nome del file _data/prodotti.yml
    template: prodotto  # layout in _layouts/prodotto.html
    dir: "prodotti"   # cartella base, sotto verrà marchio/nome
    name_expr: record['marchio-slug'] + '-' + record['nome-slug']
    title: "nome_completo"
    extension: "html"
