- nome: "Serie S"
  marchio: "Moretti Forni"
  marchio-slug: "moretti"
  nome-slug: "serie-s"
  nome_completo: "Moretti Serie S"
  descrizione: "Forno statico elettrico con tecnologia Eco SmartBaking, risparmio energetico fino al 30%, gestione intuitiva e design in acciaio inox. Ideale per pizza, pane e pasticceria."
  tipo: "forno statico"
  ambito: 
    - pizzeria
    - panificazione
    - pasticceria
  cartella_immagini: prodotti/moretti-forni
  immagini:
    - "moretti-serie-s-primo-piano.webp"
    - "colonna-serie-s-con-lievitatore-e-cappa.webp"

- nome: "Neapolis"
  marchio: "Moretti Forni"
  marchio-slug: "moretti"
  nome-slug: "neapolis"
  nome_completo: "Moretti Neapolis 510°C"
  descrizione: "Il forno elettrico per pizza napoletana più potente al mondo, raggiunge 510°C per una cottura perfetta in meno di un minuto."
  tipo: "forno statico"
  ambito:
    - pizzeria
  cartella_immagini: prodotti/moretti-forni
  immagini:
    - "neapolis.webp"
    - "neapolis-dettaglio.webp"

- nome: "Serie P"
  marchio: "Moretti Forni"
  marchio-slug: "moretti"
  nome-slug: "serie-p"
  nome_completo: "Moretti Serie P"
  descrizione: "Forno statico versatile e robusto, ideale per pizza al taglio, in pala e panificazione. Controlli elettronici avanzati e alta affidabilità."
  tipo: "forno statico"
  ambito:
    - pizzeria
    - panificazione
  cartella_immagini: prodotti/moretti-forni
  immagini:
    - "moretti-serie-P.webp"

- nome: "Cheftop Mind.Maps Plus"
  marchio: "Unox"
  marchio-slug: "unox"
  nome-slug: "cheftop-mind-maps-plus"
  nome_completo: "Unox Cheftop Mind.Maps Plus"
  descrizione: "Forno combinato professionale con tecnologia Mind.Maps™, cotture uniformi e programmi personalizzabili. Perfetto per ristorazione e gastronomie."
  tipo: "forno combinato"
  ambito:
    - ristorazione
    - gastronomia
    - pasticceria
  cartella_immagini: prodotti/unox
  immagini:
    - "colonna-5-teglie-3-teglie.webp"
    - "colonna-cheftop-3-teglie.webp"
    - "cheftop-5-teglie-stand-alto.webp"

- nome: "Bakertop Mind.Maps Plus"
  marchio: "Unox"
  marchio-slug: "unox"
  nome-slug: "bakertop-mind-maps-plus"
  nome_completo: "Unox Bakertop Mind.Maps Plus"
  descrizione: "Forno combinato Unox specifico per panificazione e pasticceria, con cottura uniforme, risparmio energetico e controllo totale del processo."
  tipo: "forno combinato"
  ambito:
    - panificazione
    - pasticceria
  cartella_immagini: prodotti/unox
  immagini:
    - "bakertop-10-teglie.webp"
    - "bakertop-carrellato.webp"

- nome: "Cheftop X"
  marchio: "Unox"
  marchio-slug: "unox"
  nome-slug: "cheftop-x"
  nome_completo: "Unox Cheftop X"
  descrizione: "Nuova generazione di forni combinati Unox: più intuitivi, connessi e sostenibili, per performance professionali in cucina."
  tipo: "forno combinato"
  ambito:
    - ristorazione
    - gastronomia
  cartella_immagini: prodotti/unox
  immagini:
    - "cheftop-x.webp"
    - "interactive-cooking-cheftop-x.webp"

- nome: "Modi"
  marchio: "Coldline"
  marchio-slug: "coldline"
  nome-slug: "modi-abbattitore"
  nome_completo: "Coldline Modi"
  descrizione: "Abbattitore di temperatura per la conservazione e il raffreddamento rapido degli alimenti."
  tipo: "abbattitore"
  ambito:
    - ristorazione
    - gastronomia
    - pasticceria
  cartella_immagini: prodotti/coldline
  immagini:
    - "abbattitore-coldline-modi.webp"

- nome: "Levtronic"
  marchio: "Coldline"
  marchio-slug: "coldline"
  nome-slug: "levtronic-fermalievita"
  nome_completo: "Coldline Levtronic"
  descrizione: "Sistema di fermalievitazione controllata per la panificazione e la pasticceria."
  tipo: "fermalievita"
  ambito:
    - panificazione
    - pasticceria
  cartella_immagini: prodotti/coldline
  immagini:
    - "fermalievitazione-armadi-e-tavoli-levtronic-coldline.webp"
    #- "levtronic-fermalievita.webp"

- nome: "Armadi Frigo Master"
  marchio: "Coldline"
  marchio-slug: "coldline"
  nome-slug: "armadi-frigo-master"
  nome_completo: "Coldline Armadi Frigo Master"
  descrizione: "Armadi frigoriferi professionali per la conservazione ottimale degli alimenti."
  tipo: "armadio frigo"
  ambito:
    - ristorazione
    - gastronomia
    - pasticceria
  cartella_immagini: prodotti/coldline
  immagini:
    - "armadio-frigorifero-Master-Coldline.webp"

- nome: "Lavabicchieri Uniko"
  marchio: "Krupps"
  marchio-slug: "krupps"
  nome-slug: "lavabicchieri-uniko"
  nome_completo: "Krupps Lavabicchieri Uniko"
  descrizione: "Lavabicchieri professionale per una pulizia rapida ed efficace."
  tipo: "lavabicchieri"
  ambito:
    - ristorazione
    - bar
  cartella_immagini: prodotti/krupps
  immagini:
    - "lavabicchieri-krupps-uniko-EL42E.webp"

# KRUPPS-capotte-EL60E

- nome: "Lavastoviglie Capotte Uniko"
  marchio: "Krupps"
  marchio-slug: "krupps"
  nome-slug: "lavastoviglie-capotte-uniko"
  nome_completo: "Krupps Lavastoviglie Capotte Uniko"
  descrizione: "Lavastoviglie a capotta professionale per una pulizia efficiente e risparmio energetico."
  tipo: "lavastoviglie"
  ambito:
    - ristorazione
    - bar
  cartella_immagini: prodotti/krupps
  immagini:
    - "KRUPPS-capotte-EL60E.webp"
    - "capotte-e-sistema-osmosi.webp"

- nome: "Lavastoviglie a carico frontale Uniko"
  marchio: "Krupps"
  marchio-slug: "krupps"
  nome-slug: "lavastoviglie-carico-frontale-uniko"
  nome_completo: "Krupps Lavastoviglie a carico frontale Uniko"
  descrizione: "Lavastoviglie a carico frontale professionale per una pulizia efficace e risparmio energetico."
  tipo: "lavastoviglie"
  ambito:
    - ristorazione
    - bar
    - pasticceria
  cartella_immagini: prodotti/krupps
  immagini:
    - "zona-lavaggio-krupps.webp"
    - "capotte-lavastoviglie-sistema-osmosi.webp"

- nome: "Cucine Monoblocco"
  marchio: "Giorik"
  marchio-slug: "giorik"
  nome-slug: "cucine-monoblocco"
  nome_completo: "Cucine Monoblocco Giorik"
  descrizione: "Cucine monoblocco professionali personalizzabili su misura per ogni esigenza."
  tipo: "cucina"
  ambito:
    - ristorazione
    - gastronomia
  cartella_immagini: prodotti/giorik
  immagini:
    - "giorik-cucina-monoblocco.webp"

- nome: "Forno Combinato Connesso"
  marchio: "Giorik"
  marchio-slug: "giorik"
  nome-slug: "forno-combinato-connesso"
  nome_completo: "Giorik Forno Combinato Connesso"
  descrizione: "Forno combinato professionale connesso per una gestione intelligente della cottura."
  tipo: "forno combinato"
  ambito:
    - ristorazione
    - gastronomia
    - pasticceria
  cartella_immagini: prodotti/giorik
  immagini:
    - "forno-combinato-giorik.webp"

- nome: "Cucina a gas modulare"
  marchio: "Giorik"
  marchio-slug: "giorik"
  nome-slug: "cucina-gas-modulare"
  nome_completo: "Giorik Cucina a gas Modulare"
  descrizione: "Sistema di cottura modulare professionale per una flessibilità ottimale in cucina."
  tipo: "cucina"
  ambito:
    - ristorazione
    - gastronomia
  cartella_immagini: prodotti/giorik
  immagini:
    - "01-cucinagas-giorik.webp"
